<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Gabriel Bider</Authors>
    <PackageTags>compound document ole olecdf cdf cfbf com structured storage binary</PackageTags>
    <Copyright>Copyright © 2026</Copyright>
    <PackageProjectUrl>https://github.com/silkfire/LiteCDF</PackageProjectUrl>
    <Description>A high performance compound document format (CDF) reader.</Description>
    <DocumentationFile>./LiteCDF.xml</DocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
    <Version>5.1.1</Version>
    <AssemblyVersion>5.1.1.0</AssemblyVersion>
    <PackageReleaseNotes>5.1.1 Performance improvements</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BinaryBuffers" Version="5.0.0" />
    <PackageReference Include="StreamExtensions" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Visible>False</Visible>
    </None>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Visible>False</Visible>
    </None>
    <None Include="..\icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Visible>False</Visible>
    </None>
  </ItemGroup>

</Project>
